import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import Footer from "../components/Footer";
import Themeproviders from "@/components/config/providers";
import TopNav from "@/components/TopNav";

export const metadata = {
  title: "TopDev",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <Themeproviders>
          <TopNav />
          <NavBar />
          {children}
          <Footer />
        </Themeproviders>
      </body>
    </html>
  );
}
